# Generated by Django 4.1 on 2024-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='entries',
            name='audio_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
